---
- name: Create .ssh directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: "0700"

- name: Decrypt and copy SSH config
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/crypted/ssh/config"
    dest: "{{ ansible_user_dir }}/.ssh/config"
    mode: "0644"
    decrypt: true

- name: Decrypt and copy private key
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/crypted/ssh/id_rsa_perso_github"
    dest: "{{ ansible_user_dir }}/.ssh/id_rsa_perso_github"
    mode: "0600"
    decrypt: true

- name: Decrypt and copy public key
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/crypted/ssh/id_rsa_perso_github.pub"
    dest: "{{ ansible_user_dir }}/.ssh/id_rsa_perso_github.pub"
    mode: "0644"
    decrypt: true

- name: Decrypt and copy public key
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/crypted/ssh/known_hosts"
    dest: "{{ ansible_user_dir }}/.ssh/known_hosts"
    mode: "0644"
    decrypt: true
