---
- name: Create folder tree structure
  hosts: localhost
  tasks:
    - name: Create folders in the operating system
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        mode: "{{ item.mode | default('0755') }}"
        owner: "{{ item.owner | default('root') }}"
      loop:
        - path: "{{ ansible_env.HOME }}/Documents/Projects"
          owner: "{{ ansible_env.USER }}"
        - path: "{{ ansible_env.HOME }}/Documents/Rapports"
          owner: "{{ ansible_env.USER }}"
        - path: "{{ ansible_env.HOME }}/Documents/RunJS"
          owner: "{{ ansible_env.USER }}"
        - path: "{{ ansible_env.HOME }}/Pictures/Screenshots"
          owner: "{{ ansible_env.USER }}"
