---
- name: MacOS configuration
  hosts: localhost
  tasks:
    # DOCK Configuration
    - name: Set dock icon size
      community.general.osx_defaults:
        domain: com.apple.dock
        key: tilesize
        type: int
        value: 61

    - name: Set minimize animation effect to scale
      community.general.osx_defaults:
        domain: com.apple.dock
        key: mineffect
        type: string
        value: scale

    - name: Set active applications only in dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: static-only
        type: bool
        value: true

    # SCREENSHOTS Configuration
    - name: Set screenshot location
      community.general.osx_defaults:
        domain: com.apple.screencapture
        key: location
        type: string
        value: ~/Pictures/Screenshots

    # FINDER Configuration
    - name: Show extensions in Finder
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: AppleShowAllExtensions
        type: bool
        value: true

    - name: Show hidden files in Finder
      community.general.osx_defaults:
        domain: com.apple.finder
        key: AppleShowAllFiles
        type: bool
        value: true

    - name: Set Finder default view style to list
      community.general.osx_defaults:
        domain: com.apple.finder
        key: FXPreferredViewStyle
        type: string
        value: Nlsv

    - name: Keep folders on top in Finder
      community.general.osx_defaults:
        domain: com.apple.finder
        key: _FXSortFoldersFirst
        type: bool
        value: true

    - name: Set Finder to empty trash automatically after 30 days
      community.general.osx_defaults:
        domain: com.apple.finder
        key: FXRemoveOldTrashItems
        type: bool
        value: true

    - name: Change file extension warning in Finder
      community.general.osx_defaults:
        domain: com.apple.finder
        key: FXEnableExtensionChangeWarning
        type: bool
        value: false

    - name: Set Finder to save new documents to iCloud
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSDocumentSaveNewDocumentsToCloud
        type: bool
        value: false

    - name: Set Finder sidebar icon size
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSTableViewDefaultSizeMode
        type: int
        value: 3

    # DESKTOP Configuration
    - name: Keep folders on top on Desktop
      community.general.osx_defaults:
        domain: com.apple.finder
        key: _FXSortFoldersFirstOnDesktop
        type: bool
        value: true

    - name: Hide all icons on Desktop
      community.general.osx_defaults:
        domain: com.apple.finder
        key: CreateDesktop
        type: bool
        value: false

    # MENU BAR Configuration
    - name: Disable Music song notifications
      community.general.osx_defaults:
        domain: com.apple.Music
        key: userWantsPlaybackNotifications
        type: bool
        value: false

    # MOUSE Configuration
    - name: Enable Focus Follow Mouse in Terminal
      community.general.osx_defaults:
        domain: com.apple.Terminal
        key: FocusFollowsMouse
        type: bool
        value: true

    # KEYBOARD Configuration
    - name: Set Fn key usage to control
      community.general.osx_defaults:
        domain: com.apple.HIToolbox
        key: AppleFnUsageType
        type: int
        value: 2

    # MISSION CONTROL Configuration
    - name: Disable auto rearrange spaces in Mission Control
      community.general.osx_defaults:
        domain: com.apple.dock
        key: mru-spaces
        type: bool
        value: false

    - name: Group windows by application in Mission Control
      community.general.osx_defaults:
        domain: com.apple.dock
        key: expose-group-apps
        type: bool
        value: true

    # ACTIVITY MONITOR Configuration
    - name: Set Activity Monitor icon type to show CPU usage
      community.general.osx_defaults:
        domain: com.apple.ActivityMonitor
        key: IconType
        type: int
        value: 6
