# FINDER Configuration
- name: Show extensions in Finder
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
  notify: Kill Finder

- name: Show hidden files in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
  notify: Kill Finder

- name: Set Finder default view style to list
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: Nlsv
  notify: Kill Finder

- name: Keep folders on top in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true
  notify: Kill Finder

- name: Set Finder to empty trash automatically after 30 days
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXRemoveOldTrashItems
    type: bool
    value: true
  notify: Kill Finder

- name: Change file extension warning in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false
  notify: Kill Finder

- name: Hide all icons on Desktop
  community.general.osx_defaults:
    domain: com.apple.finder
    key: CreateDesktop
    type: bool
    value: false
  notify: Kill Finder

- name: Set Finder to save new documents to iCloud
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
  notify: Kill Finder

- name: Set Finder sidebar icon size
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSTableViewDefaultSizeMode
    type: int
    value: 3
  notify: Kill Finder

- name: Keep folders on top on Desktop
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirstOnDesktop
    type: bool
    value: true
  notify: Kill Finder
