- name: Install MonoLisa fonts on macOS
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/Library/Fonts/"
    mode: "0644"
  loop:
    - "{{ playbook_dir }}/fonts/monolisa/MonoLisa-Bold.ttf"
    - "{{ playbook_dir }}/fonts/monolisa/MonoLisa-BoldItalic.ttf"
    - "{{ playbook_dir }}/fonts/monolisa/MonoLisa-Light.ttf"
    - "{{ playbook_dir }}/fonts/monolisa/MonoLisa-LightItalic.ttf"
    - "{{ playbook_dir }}/fonts/monolisa/MonoLisa-Medium.ttf"
    - "{{ playbook_dir }}/fonts/monolisa/MonoLisa-MediumItalic.ttf"
    - "{{ playbook_dir }}/fonts/monolisa/MonoLisa-Regular.ttf"
    - "{{ playbook_dir }}/fonts/monolisa/MonoLisa-RegularItalic.ttf"
    - "{{ playbook_dir }}/fonts/monolisa/MonoLisa-SemiBold.ttf"
    - "{{ playbook_dir }}/fonts/monolisa/MonoLisa-SemiBoldItalic.ttf"

- name: Install FiraCode fonts on macOS
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/Library/Fonts/"
    mode: "0644"
  loop:
    - "{{ playbook_dir }}/fonts/firacode/FiraCode-Bold.ttf"
    - "{{ playbook_dir }}/fonts/firacode/FiraCode-Light.ttf"
    - "{{ playbook_dir }}/fonts/firacode/FiraCode-Medium.ttf"
    - "{{ playbook_dir }}/fonts/firacode/FiraCode-Regular.ttf"
    - "{{ playbook_dir }}/fonts/firacode/FiraCode-SemiBold.ttf"
    - "{{ playbook_dir }}/fonts/firacode/FiraCode-VariableFont_wght.ttf"

- name: Install Inter fonts on macOS
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/Library/Fonts/"
    mode: "0644"
  loop:
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-Black.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-BlackItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-Bold.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-BoldItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-ExtraBold.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-ExtraBoldItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-ExtraLight.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-ExtraLightItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-Italic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-Light.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-LightItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-Medium.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-MediumItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-Regular.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-SemiBold.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-SemiBoldItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-Thin.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_18pt-ThinItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-Black.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-BlackItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-Bold.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-BoldItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-ExtraBold.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-ExtraBoldItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-ExtraLight.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-ExtraLightItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-Italic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-Light.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-LightItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-Medium.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-MediumItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-Regular.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-SemiBold.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-SemiBoldItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-Thin.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_24pt-ThinItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-Black.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-BlackItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-Bold.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-BoldItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-ExtraBold.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-ExtraBoldItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-ExtraLight.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-ExtraLightItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-Italic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-Light.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-LightItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-Medium.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-MediumItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-Regular.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-SemiBold.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-SemiBoldItalic.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-Thin.ttf"
    - "{{ playbook_dir }}/fonts/inter/Inter_28pt-ThinItalic.ttf"
